markdown: kramdown
highlighter:      rouge
encoding: UTF-8

title: Tufte
tagline: 'Working Papers'
description: 'Working Papers <br /> ISSN (En Trámite)'
url: https://tuftepapers.com
baseurl: '/'

author:
  name: 'Bastián González-Bustamante'
  url: https://twitter.com/bastiangb

paginate: 5
## paginate_path: '/page:num'
## Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

sidebar_home_link: true
# sidebar_blog_link: '/blog'

google_analytics: UA-154958231-2

hydeout:
  version:          4.1.0
  repo:             https://github.com/fongandrew/hydeout

remote_theme: fongandrew/hydeout